controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    projectile = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . 2 2 2 2 . . . . . . . . . 
        . . 2 5 5 5 5 4 2 2 . . . . . . 
        . . 5 5 5 5 5 5 5 4 2 2 4 4 2 . 
        . . 5 5 5 5 5 5 5 5 5 5 5 5 4 . 
        . . 5 5 5 5 5 5 5 5 4 4 4 4 2 . 
        . . 5 5 5 5 5 5 4 4 2 2 . . . . 
        . . 2 5 5 5 5 2 2 . . . . . . . 
        . . . 2 2 2 2 . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, spacePlane, 200, 0)
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function (sprite, otherSprite) {
    otherSprite.destroy(effects.fire, 500)
    info.changeScoreBy(1)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    otherSprite.destroy()
    scene.cameraShake(4, 500)
    info.changeLifeBy(-1)
})
let bogey: Sprite = null
let projectile: Sprite = null
let spacePlane: Sprite = null
spacePlane = sprites.create(img`
    ......ccc.........ffffff....
    .2....f6cc.......fcc88ff....
    .42...f66cc...fffccccff.....
    .542..f866cccc88886668cc....
    ..542.f886cc8888888866b9c...
    .52222cf8888888888888b999c..
    ..542c88c888888888b11199b8c.
    .542f88ccccccc888899111b888c
    .42.fffffcc888c888888888888f
    .2.......f8888668888888888f.
    ........f888866fc8888888ff..
    .......c888866ffffffffff....
    .......c8888cff.............
    .......fffffff..............
    ............................
    ............................
    ............................
    ............................
    ............................
    ............................
    `, SpriteKind.Player)
controller.moveSprite(spacePlane, 200, 200)
spacePlane.setStayInScreen(true)
info.setLife(3)
game.onUpdateInterval(500, function () {
    bogey = sprites.create(img`
        ........................
        ........................
        ..........fff...........
        .........ffff...........
        .....fffffff..fff.......
        ...ffaaaaaaffffff.......
        ..faaaaaaaaaafff........
        .faaaaaaaaaaaaf..ff.....
        faaaaa1ffaaaaaaffff.....
        faadaaffaaaaaaaaff......
        faaaaaaaaaaaaaaaa6......
        .f667166aaaaccaaa6.ff...
        .fa7776aaacccccaacfff...
        .fa776aacccccccccc6.....
        .faaaaccc66aa6cccccfff..
        ..ffff6666aaa6cccccfff..
        ...fcf6faaaa6ccccccff...
        ....ff6faa6facccccc6ffff
        .....f66ffaaaacccccccccf
        .....ff666aaacc6ccccccf.
        .....fcf6faacc666cccff..
        ...ffcccffcccc6f66ff....
        ...ffffffcaaaccfff......
        ........ffffffff........
        `, SpriteKind.Enemy)
    bogey.setVelocity(-100, 0)
    bogey.setPosition(160, randint(5, 115))
    bogey.setFlag(SpriteFlag.AutoDestroy, true)
})
